# Issue Templates

- [Bug Report](/.github/ISSUE_TEMPLATE/bug_report.yml): For reporting bugs and unexpected behavior.
- [Feature Request](/.github/ISSUE_TEMPLATE/feature_request.yml): For suggesting new features or enhancements.
